/* This file is generated by scripts/generate-presence-registry.mjs. */
import type { PresenceDefinition } from "../types.js";

import presenceC_Crunchyroll from "../C/Crunchyroll/presence.js";
import presenceG_GitHub from "../G/GitHub/presence.js";
import presenceN_Netflix from "../N/Netflix/presence.js";
import presenceS_Spotify from "../S/Spotify/presence.js";
import presenceT_Twitch from "../T/Twitch/presence.js";
import presenceY_YouTube from "../Y/YouTube/presence.js";

export const presenceRegistry = [
  presenceC_Crunchyroll,
  presenceG_GitHub,
  presenceN_Netflix,
  presenceS_Spotify,
  presenceT_Twitch,
  presenceY_YouTube,
] as const satisfies readonly PresenceDefinition[];
