/* This file is generated by scripts/generate-presence-registry.mjs. */
import type { PresenceDefinition } from "../types.js";

import presenceT_Twitch from "../T/Twitch/presence.js";
import presenceY_YouTube from "../Y/YouTube/presence.js";

export const presenceRegistry = [
  presenceT_Twitch,
  presenceY_YouTube,
] as const satisfies readonly PresenceDefinition[];
